#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Gifaroo.Android.Resource", IsApplication=true)]

namespace Gifaroo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InAppBilling.Resource.String.library_name = global::Gifaroo.Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int font_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int dark_blue = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_blur_1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_blur_10 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_blur_11 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_blur_12 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_blur_13 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_blur_14 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_blur_15 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_blur_16 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_blur_17 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_blur_2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_blur_3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg_blur_4 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bg_blur_5 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bg_blur_6 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bg_blur_7 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bg_blur_8 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bg_blur_9 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bg_gifaroo_1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bg_gifaroo_10 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bg_gifaroo_11 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bg_gifaroo_12 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int bg_gifaroo_13 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int bg_gifaroo_14 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int bg_gifaroo_15 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int bg_gifaroo_16 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int bg_gifaroo_17 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int bg_gifaroo_18 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int bg_gifaroo_19 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int bg_gifaroo_2 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int bg_gifaroo_20 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int bg_gifaroo_21 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int bg_gifaroo_3 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int bg_gifaroo_4 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int bg_gifaroo_5 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int bg_gifaroo_6 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int bg_gifaroo_7 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int bg_gifaroo_8 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int bg_gifaroo_9 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int bg_Gradient_1 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int bg_Gradient_10 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int bg_Gradient_11 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int bg_Gradient_12 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int bg_Gradient_13 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int bg_Gradient_14 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int bg_Gradient_15 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int bg_Gradient_16 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int bg_Gradient_17 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int bg_Gradient_18 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int bg_Gradient_19 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int bg_Gradient_2 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int bg_Gradient_20 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int bg_Gradient_21 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int bg_Gradient_3 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int bg_Gradient_4 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int bg_Gradient_5 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int bg_Gradient_6 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int bg_Gradient_7 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int bg_Gradient_8 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int bg_Gradient_9 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int bg_pattern_1 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int bg_pattern_10 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int bg_pattern_11 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int bg_pattern_12 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int bg_pattern_13 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int bg_pattern_14 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int bg_pattern_15 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int bg_pattern_16 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int bg_pattern_17 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int bg_pattern_18 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int bg_pattern_19 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int bg_pattern_2 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int bg_pattern_20 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int bg_pattern_21 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int bg_pattern_22 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int bg_pattern_23 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int bg_pattern_24 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int bg_pattern_25 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int bg_pattern_3 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int bg_pattern_4 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int bg_pattern_5 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int bg_pattern_6 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int bg_pattern_7 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int bg_pattern_8 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int bg_pattern_9 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int bg_shapes_1 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int bg_shapes_10 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int bg_shapes_11 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int bg_shapes_12 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int bg_shapes_13 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int bg_shapes_14 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int bg_shapes_15 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int bg_shapes_16 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int bg_shapes_17 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int bg_shapes_18 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int bg_shapes_19 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int bg_shapes_2 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int bg_shapes_20 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int bg_shapes_21 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int bg_shapes_22 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int bg_shapes_23 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int bg_shapes_24 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int bg_shapes_3 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int bg_shapes_4 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int bg_shapes_5 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int bg_shapes_6 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int bg_shapes_7 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int bg_shapes_8 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int bg_shapes_9 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int bgTitle_Blurs = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int bgTitle_Colors = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int bgTitle_Fonts = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int bgTitle_Gifaroo = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int bgTitle_Gradients = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int bgTitle_Night = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int bgTitle_Patterns = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int bucket = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int c10 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int customBorder = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int deleteX = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int effects = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int flip = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int GifarooActionbarBackground = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int GifarooActionbarBackgroundflat = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int GifarooActionbarBackgroundflatTop = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int GifarooBackgroundTile = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int gifaroologomobileheader = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int Gifarooprogressbar = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int GifarooSelectedTabBackground = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int HighlightOutline = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int ic_action_download = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int ic_action_edit = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int ic_action_gifaroo_plus = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int ic_action_gifaroo_plus_stamp = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int ic_format_color_fill_white_24dp = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int ic_gifaroo_store_white = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int ic_home_white_24dp = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int ic_save_white_24dp = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int ic_text_fields_white_24dp = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int inappicon = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int InvisibleDrawable = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int loading_placeholder = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int remove = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int scaledBackground = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int spanscale = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int zoominout = 2130837649;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a002b
			public const int BlurryPatternsStoreItem = 2131361835;
			
			// aapt resource value: 0x7f0a001a
			public const int ContentDisplayinside = 2131361818;
			
			// aapt resource value: 0x7f0a004a
			public const int ImageRelativeLayout = 2131361866;
			
			// aapt resource value: 0x7f0a003a
			public const int MainLayout = 2131361850;
			
			// aapt resource value: 0x7f0a004f
			public const int SponsoredLinearLayout = 2131361871;
			
			// aapt resource value: 0x7f0a002a
			public const int StoreItemsLinearLayout = 2131361834;
			
			// aapt resource value: 0x7f0a0024
			public const int StoreWrapper = 2131361828;
			
			// aapt resource value: 0x7f0a0008
			public const int TextControlls1 = 2131361800;
			
			// aapt resource value: 0x7f0a0054
			public const int URLBar = 2131361876;
			
			// aapt resource value: 0x7f0a0049
			public const int adLinearLayout = 2131361865;
			
			// aapt resource value: 0x7f0a001c
			public const int backgroundDisplay = 2131361820;
			
			// aapt resource value: 0x7f0a0021
			public const int backgroundImagesGrid = 2131361825;
			
			// aapt resource value: 0x7f0a0000
			public const int backgroundItem = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int backgroundLayout = 2131361807;
			
			// aapt resource value: 0x7f0a0011
			public const int backgroundSetsLinearLayout = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int backgroundSetsScrollView = 2131361808;
			
			// aapt resource value: 0x7f0a0017
			public const int bgBlurSetButton = 2131361815;
			
			// aapt resource value: 0x7f0a0012
			public const int bgColorsSetButton = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int bgGifarooSetButton = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int bgGradientsSetButton = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int bgNightSetButton = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int bgPatternsSetButton = 2131361814;
			
			// aapt resource value: 0x7f0a002c
			public const int blursPatterns_store_item_webView = 2131361836;
			
			// aapt resource value: 0x7f0a0053
			public const int callToAction = 2131361875;
			
			// aapt resource value: 0x7f0a0043
			public const int cancelDownloadButton = 2131361859;
			
			// aapt resource value: 0x7f0a0028
			public const int closeStoreButton = 2131361832;
			
			// aapt resource value: 0x7f0a001b
			public const int contentDisplay = 2131361819;
			
			// aapt resource value: 0x7f0a0020
			public const int contentDisplayLoadingTextView = 2131361824;
			
			// aapt resource value: 0x7f0a003d
			public const int countText = 2131361853;
			
			// aapt resource value: 0x7f0a0007
			public const int deleteTextButton = 2131361799;
			
			// aapt resource value: 0x7f0a0056
			public const int downloadButton = 2131361878;
			
			// aapt resource value: 0x7f0a0059
			public const int editButton = 2131361881;
			
			// aapt resource value: 0x7f0a000d
			public const int editText1 = 2131361805;
			
			// aapt resource value: 0x7f0a000b
			public const int fontSpinner = 2131361803;
			
			// aapt resource value: 0x7f0a0035
			public const int fontsStoreItem = 2131361845;
			
			// aapt resource value: 0x7f0a0037
			public const int fonts_store_item_webView = 2131361847;
			
			// aapt resource value: 0x7f0a002f
			public const int freeUnlockBlursPatternsButton = 2131361839;
			
			// aapt resource value: 0x7f0a0034
			public const int freeUnlockNightGradientButton = 2131361844;
			
			// aapt resource value: 0x7f0a001e
			public const int gifDisplay = 2131361822;
			
			// aapt resource value: 0x7f0a0030
			public const int gradientNightsStoreItem = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int gradientnights_store_item_webView = 2131361841;
			
			// aapt resource value: 0x7f0a003c
			public const int gridLinearLayout = 2131361852;
			
			// aapt resource value: 0x7f0a003e
			public const int gridview = 2131361854;
			
			// aapt resource value: 0x7f0a0050
			public const int headline = 2131361872;
			
			// aapt resource value: 0x7f0a0055
			public const int homePageButton = 2131361877;
			
			// aapt resource value: 0x7f0a001f
			public const int imageView1 = 2131361823;
			
			// aapt resource value: 0x7f0a0036
			public const int imageView2 = 2131361846;
			
			// aapt resource value: 0x7f0a000c
			public const int linearLayout1 = 2131361804;
			
			// aapt resource value: 0x7f0a0009
			public const int linearLayout2 = 2131361801;
			
			// aapt resource value: 0x7f0a003f
			public const int linearLayout4 = 2131361855;
			
			// aapt resource value: 0x7f0a0026
			public const int linearLayout5 = 2131361830;
			
			// aapt resource value: 0x7f0a003b
			public const int linearLayoutTarget = 2131361851;
			
			// aapt resource value: 0x7f0a0018
			public const int lowerBorderLine = 2131361816;
			
			// aapt resource value: 0x7f0a0004
			public const int mainEditorLayout = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int mainImage = 2131361793;
			
			// aapt resource value: 0x7f0a0045
			public const int mainSaveLayout = 2131361861;
			
			// aapt resource value: 0x7f0a000e
			public const int newTextButton = 2131361806;
			
			// aapt resource value: 0x7f0a0041
			public const int playingWarning = 2131361857;
			
			// aapt resource value: 0x7f0a0044
			public const int progressBar1 = 2131361860;
			
			// aapt resource value: 0x7f0a002d
			public const int purchaseBlursPatternsButton = 2131361837;
			
			// aapt resource value: 0x7f0a0039
			public const int purchaseFontsButton = 2131361849;
			
			// aapt resource value: 0x7f0a0033
			public const int purchaseNightGradientButton = 2131361843;
			
			// aapt resource value: 0x7f0a0019
			public const int relativeLayout1 = 2131361817;
			
			// aapt resource value: 0x7f0a0023
			public const int rightSideBarProgressBar = 2131361827;
			
			// aapt resource value: 0x7f0a0058
			public const int saveButton = 2131361880;
			
			// aapt resource value: 0x7f0a0046
			public const int saveLayout = 2131361862;
			
			// aapt resource value: 0x7f0a0052
			public const int secBrandingLogo = 2131361874;
			
			// aapt resource value: 0x7f0a004b
			public const int secHqImage = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int secImage = 2131361868;
			
			// aapt resource value: 0x7f0a0002
			public const int secondaryImage = 2131361794;
			
			// aapt resource value: 0x7f0a0048
			public const int shareButton = 2131361864;
			
			// aapt resource value: 0x7f0a000a
			public const int sizeSpinner = 2131361802;
			
			// aapt resource value: 0x7f0a004e
			public const int source = 2131361870;
			
			// aapt resource value: 0x7f0a0057
			public const int storeButton = 2131361879;
			
			// aapt resource value: 0x7f0a0029
			public const int storeItemsScrollView = 2131361833;
			
			// aapt resource value: 0x7f0a0025
			public const int storeLayout = 2131361829;
			
			// aapt resource value: 0x7f0a004d
			public const int summary = 2131361869;
			
			// aapt resource value: 0x7f0a0042
			public const int tapAndHoldPrompt = 2131361858;
			
			// aapt resource value: 0x7f0a0022
			public const int textColorGrid = 2131361826;
			
			// aapt resource value: 0x7f0a0006
			public const int textLayout = 2131361798;
			
			// aapt resource value: 0x7f0a0027
			public const int textView1 = 2131361831;
			
			// aapt resource value: 0x7f0a0047
			public const int textView2 = 2131361863;
			
			// aapt resource value: 0x7f0a0051
			public const int textView3 = 2131361873;
			
			// aapt resource value: 0x7f0a002e
			public const int textViewBlursPatternsDescription = 2131361838;
			
			// aapt resource value: 0x7f0a0038
			public const int textViewFontsPackDescription = 2131361848;
			
			// aapt resource value: 0x7f0a0032
			public const int textViewgradientsNightDescription = 2131361842;
			
			// aapt resource value: 0x7f0a0003
			public const int topRelativeLayout = 2131361795;
			
			// aapt resource value: 0x7f0a001d
			public const int videoDisplay = 2131361821;
			
			// aapt resource value: 0x7f0a0005
			public const int view2 = 2131361797;
			
			// aapt resource value: 0x7f0a0040
			public const int webView1 = 2131361856;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int BackgroundItemsLayout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int EditGif = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int GifGallery = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Save = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int URLBar = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int backgroundTab = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int downloadButton = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int editButton = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int font_prompt = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int library_name = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int saveButton = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int search_hint = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int textTab = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int watermarkTab = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int MyActionBar = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MyActionBarTabs = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int MyActionBarTabsText = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int Theme_GifarooTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
